version: "3.9"
services:

  complexify_api:
    build:
      context: ./.
      target: complexify_api
    #networks:
    #  - complexify_public
    ports:
      - "5000:5000"
    #command: [ "python3", "/app/complexify/web/app.py" ]
    restart: unless-stopped
    volumes:
      - db:/db/

  job_flow:
    build:
      context: ./.
      target: job_flow
    ports:
      - "1000-1100:1000-1100"
    # Mounted for demo testing, probably won't in production
    volumes:
      - ./demo/:/demo/

  catalog_server:
    build:
      context: ./.
      target: cat_server
    ports:
      - "9097:9097"
    #networks:
    #  - workflow
    restart: unless-stopped
    command: ["catalog_server", "-p", "9097"]

  worker:
    build:
      context: ./.
      target: worker
    #networks:
    #  - workflow
    restart: unless-stopped
    command: ["work_queue_factory", "-T", "local", "-M", "lm.\\*", "--debug=all", "--catalog=catalog_server:9097"]
    # I mount the demo directory if I need to test one of the tools installed directly
    #volumes:
    #  - ./demo/:/demo/

#networks:
#  workflow:
#  jobconfigs:

volumes:
  #jobdata:
  #config_files:
  #user_data:
  #lmdata:
  db:  # Contains the sqlite3 database for job configurations.
