version: "3.9"
services:
  catalog_server:
    build:
      context: ./.
      target: cat_server
    ports:
      - "9097:9097"
    command: ["catalog_server", "-p", "9097"]
  worker:
    build:
      context: ./.
      target: worker
    command: ["work_queue_factory", "-T", "local", "-M", "lm*", "--catalog=catalog_server:9097"]
